import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Nabvar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.home}>
        <div className={styles.main}>
          <h1>HomePage</h1><br/>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, 
            nobis commodi! Et, beatae. Quidem, fugit. Excepturi quae, cupiditate 
            quaerat impedit laudantium, nesciunt vel tempora fugit officiis consectetur 
            similique voluptas vero.</p><br/>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, 
            nobis commodi! Et, beatae. Quidem, fugit. Excepturi quae, cupiditate 
            quaerat impedit laudantium, nesciunt vel tempora fugit officiis consectetur 
            similique voluptas vero.</p>
          </div>
      </div>
    </div>
  )
}
