import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { motion } from "framer-motion";
import { homecontainer, homeh2, homebtn, card } from "../components/Animations";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div className={styles.home}
          variants={homecontainer}
          initial="hidden"
          animate="show"
          exit="hide"
      >
        <motion.div variants={card}>
        <motion.h2 variants={homeh2}>Next.js Gallary Project</motion.h2><br/>
            <Link href="/about">
              <motion.button variants={homebtn}>About</motion.button>
            </Link>
            <Link href="/works">
              <motion.button variants={homebtn}>Works</motion.button>
            </Link>
            <Link href="/gallary">
              <motion.button variants={homebtn}>Gallary</motion.button>
            </Link>
        </motion.div>
        
      </motion.div>
    </div>
  )
}
